name: Docker Image CI

on:
  schedule:
  - cron:  '30 5,17 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: PHP version check
      run:  php -v
    - name: Mongodb driver check
      run:  php -m | grep mongo
    - name: Mysql Driver check
      run: php -m | grep mysqli
    - name: Composer test
      run: composer
    # - name: Laravel8 test
    #   run:  composer create-project --prefer-dist laravel/laravel:^8.0
    - name: test - list todos
      run: >
          curl
          --silent
          --show-error
          --fail
          "localhost:5111"
    - name: test - create todo
      run: >
          curl
          --request POST
          --header "Content-Type: application/json"
          --data '{"title":"test","description":"test","completed": false}'
          --silent
          --show-error
          --fail
          "localhost:5111"