name: Docker Image CI

on:
  schedule:
  - cron:  '30 5,17 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: PHP version check
      run:  php -v
    - name: Mongodb driver check
      run:  php -m | grep mongo
    - name: Mysql Driver check
      run: php -m | grep mysqli
    - name: Composer test
      run: composer
    - name: Testing page
      run:  echo "<?php phpinfo(); ?>" >> git update-index --chmod=+x /var/www/index.php
    - name: Test
      run: docker run --network container:nginx appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5111/public/
    - name: Removed Index file
      run:  rm -rf /var/www/index.php
    - name: Laravel8 test
      run:  composer create-project --prefer-dist laravel/laravel:^8.0
    